---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: web
    run_list:
      - recipe[go-app-configmanagement::default]
      - recipe[go-app-configmanagement::nginx]
  - name: app
    run_list:
      - recipe[go-app-configmanagement::default]
      - recipe[go-app-configmanagement::go-app]
