name             'go-app-configmanagement'
maintainer       'Nico Engelen'
maintainer_email 'engelen.nico@googlemail.com'
license          'All rights reserved'
description      'Installs/Configures go-app-configmanagement'
long_description 'Installs/Configures go-app-configmanagement'
version          '0.1.1'
issues_url       'https://github.com/nick-o/go-app-configmanagement/issues'
source_url       'https://github.com/nick-o/go-app-configmanagement/'

depends 'chef-client'
depends 'apt'

depends 'nginx', '~>2.7.6'
depends 'supervisor', '~>0.4.12'
depends 'chef-sugar', '~> 3.4.0'
