name             'go-app-configmanagment'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures go-app-configmanagment'
long_description 'Installs/Configures go-app-configmanagment'
version          '0.1.0'
